export const MOVIE_CARD_WIDTH = 150;
export const MOVIE_CARD_HEIGHT = 230;

export const MOVIE_CARD_WIDTH_MOBILE = 100;
export const MOVIE_CARD_HEIGTH_MOBILE = 150;

export const MOVIE_PAGE_CARD_WIDTH = 175;
export const MOVIE_PAGE_CARD_HEIGHT = 255;

export const MOVIE_PAGE_CARD_WIDTH_MOBILE = 125;
export const MOVIE_PAGE_CARD_HEIGTH_MOBILE = 185;

export const MINI_MOVIE_CARD_WIDTH = 60;
export const MINI_MOVIE_CARD_HEIGTH = 85;
